import { Registrant, Grade } from '@/types';

interface PdfData {
  studentName: string;
  studentEmail: string;
  projectTitle: string;
  submissionId: string;
  submissionDate: string;
  fileName: string;
  status: string;
  grade?: Grade;
}

// Generate PDF content as a properly formatted PDF string
export function generateSubmissionPdf(data: PdfData): string {
  const {
    studentName,
    studentEmail,
    projectTitle,
    submissionId,
    submissionDate,
    fileName,
    status,
    grade,
  } = data;

  // Format the date
  const formattedDate = new Date(submissionDate).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // Build grade section
  let gradeInfo = 'Not graded yet';
  let feedbackInfo = 'No feedback available';
  
  if (grade) {
    if (grade.stars && grade.stars > 0) {
      gradeInfo = `${grade.stars} / 5 Stars`;
    } else {
      gradeInfo = `${grade.score} / ${grade.maxScore} Points`;
    }
    
    if (grade.feedback && grade.feedback.trim()) {
      feedbackInfo = grade.feedback;
    }
  }

  // Map status to English
  const statusMap: Record<string, string> = {
    'مسجل': 'Registered',
    'جاري العمل': 'In Progress',
    'تم التسليم': 'Submitted',
  };
  const statusEnglish = statusMap[status] || status;

  // Build text content for PDF
  const textContent = `
STUDENT SUBMISSION REPORT
========================

Generated on: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

-------------------------------------------
STUDENT INFORMATION
-------------------------------------------
Full Name: ${studentName}
Email: ${studentEmail}

-------------------------------------------
PROJECT INFORMATION
-------------------------------------------
Project Title: ${projectTitle}

-------------------------------------------
SUBMISSION DETAILS
-------------------------------------------
Submission ID: ${submissionId}
Submission Date: ${formattedDate}
File Name: ${fileName}
Status: ${statusEnglish}

-------------------------------------------
GRADE & FEEDBACK
-------------------------------------------
Grade: ${gradeInfo}

Admin Feedback:
${feedbackInfo}

-------------------------------------------

This document was automatically generated by the Student Submission Management System.
`;

  // Create a valid PDF with embedded text
  // Using PDF 1.4 format with proper text streams
  const pdfContent = createValidPdf(textContent);
  
  return pdfContent;
}

// Create a valid PDF document with text content
function createValidPdf(textContent: string): string {
  // Split content into lines
  const lines = textContent.split('\n').filter(line => line !== undefined);
  
  // PDF requires escaping special characters in strings
  const escapeText = (text: string): string => {
    return text
      .replace(/\\/g, '\\\\')
      .replace(/\(/g, '\\(')
      .replace(/\)/g, '\\)')
      .replace(/\r/g, '');
  };

  // Build text drawing commands
  let yPosition = 750;
  const lineHeight = 14;
  let textCommands = '';
  
  for (const line of lines) {
    if (yPosition < 50) {
      // Would need new page, but for simplicity we'll just continue
      break;
    }
    
    const escapedLine = escapeText(line);
    
    // Check if it's a header line
    if (line.includes('===') || line.includes('---')) {
      // Skip divider lines visually but keep spacing
      yPosition -= lineHeight / 2;
      continue;
    }
    
    if (line === 'STUDENT SUBMISSION REPORT' || 
        line.includes('STUDENT INFORMATION') ||
        line.includes('PROJECT INFORMATION') ||
        line.includes('SUBMISSION DETAILS') ||
        line.includes('GRADE & FEEDBACK')) {
      // Header text - bold simulation with larger font
      textCommands += `BT\n/F1 14 Tf\n50 ${yPosition} Td\n(${escapedLine}) Tj\nET\n`;
      yPosition -= lineHeight + 4;
    } else if (line.trim()) {
      // Regular text
      textCommands += `BT\n/F1 11 Tf\n50 ${yPosition} Td\n(${escapedLine}) Tj\nET\n`;
      yPosition -= lineHeight;
    } else {
      // Empty line - just add spacing
      yPosition -= lineHeight / 2;
    }
  }

  const streamLength = textCommands.length;

  const pdf = `%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj

2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj

3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>
endobj

4 0 obj
<< /Length ${streamLength} >>
stream
${textCommands}endstream
endobj

5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj

xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000266 00000 n 
0000000${(317 + streamLength).toString().padStart(3, '0')} 00000 n 
trailer
<< /Size 6 /Root 1 0 R >>
startxref
${380 + streamLength}
%%EOF`;

  return pdf;
}

// Helper to get registrant data formatted for PDF
export function formatRegistrantForPdf(registrant: Registrant, file: { name: string }): PdfData {
  return {
    studentName: registrant.nameEn.replace(/_/g, ' '),
    studentEmail: registrant.email,
    projectTitle: registrant.projectTitleEn.replace(/_/g, ' '),
    submissionId: registrant.id,
    submissionDate: registrant.registrationDate,
    fileName: file.name,
    status: registrant.status,
    grade: registrant.grade,
  };
}
