import { Grade } from '@/types';

interface PdfData {
  studentName: string;
  studentEmail: string;
  projectTitle: string;
  submissionId: string;
  submissionDate: string;
  fileName: string;
  status: string;
  grade?: Grade;
}

// Generate a valid PDF with embedded text content
export function generateSubmissionPdf(data: PdfData): ArrayBuffer {
  const {
    studentName,
    studentEmail,
    projectTitle,
    submissionId,
    submissionDate,
    fileName,
    status,
    grade,
  } = data;

  // Format the date
  const formattedDate = new Date(submissionDate).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // Build grade section
  let gradeInfo = 'Not available';
  let feedbackInfo = 'Not available';
  
  if (grade) {
    if (grade.stars && grade.stars > 0) {
      gradeInfo = `${grade.stars} / 5 Stars`;
    } else if (grade.score !== undefined) {
      gradeInfo = `${grade.score} / ${grade.maxScore} Points`;
    }
    
    if (grade.feedback && grade.feedback.trim()) {
      feedbackInfo = grade.feedback;
    }
  }

  // Map status to English
  const statusMap: Record<string, string> = {
    'مسجل': 'Registered',
    'جاري العمل': 'In Progress',
    'تم التسليم': 'Submitted',
  };
  const statusEnglish = statusMap[status] || status || 'Not available';

  // Sanitize all text values
  const safeText = (text: string | undefined | null): string => {
    if (!text || text.trim() === '') return 'Not available';
    // Remove non-ASCII characters and escape special PDF characters
    return text
      .replace(/[^\x20-\x7E]/g, '')
      .replace(/\\/g, '\\\\')
      .replace(/\(/g, '\\(')
      .replace(/\)/g, '\\)');
  };

  const safeName = safeText(studentName);
  const safeEmail = safeText(studentEmail);
  const safeProject = safeText(projectTitle);
  const safeSubmissionId = safeText(submissionId);
  const safeFileName = safeText(fileName);
  const safeGrade = safeText(gradeInfo);
  const safeFeedback = safeText(feedbackInfo);
  const safeStatus = safeText(statusEnglish);
  const safeDate = safeText(formattedDate);
  const generatedDate = safeText(new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  }));

  // Build the content stream with text positioning
  const contentStream = `
BT
/F1 18 Tf
50 750 Td
(STUDENT SUBMISSION REPORT) Tj
0 -30 Td
/F1 10 Tf
(Generated on: ${generatedDate}) Tj
0 -40 Td
/F1 14 Tf
(STUDENT INFORMATION) Tj
0 -25 Td
/F1 11 Tf
(Full Name: ${safeName}) Tj
0 -18 Td
(Email: ${safeEmail}) Tj
0 -35 Td
/F1 14 Tf
(PROJECT INFORMATION) Tj
0 -25 Td
/F1 11 Tf
(Project Title: ${safeProject}) Tj
0 -35 Td
/F1 14 Tf
(SUBMISSION DETAILS) Tj
0 -25 Td
/F1 11 Tf
(Submission ID: ${safeSubmissionId}) Tj
0 -18 Td
(Submission Date: ${safeDate}) Tj
0 -18 Td
(File Name: ${safeFileName}) Tj
0 -18 Td
(Status: ${safeStatus}) Tj
0 -35 Td
/F1 14 Tf
(GRADE AND FEEDBACK) Tj
0 -25 Td
/F1 11 Tf
(Grade: ${safeGrade}) Tj
0 -18 Td
(Admin Feedback: ${safeFeedback}) Tj
0 -50 Td
/F1 9 Tf
(This document was automatically generated by the Student Submission Management System.) Tj
ET
`.trim();

  // Build the PDF structure
  const objects: string[] = [];
  
  // Object 1: Catalog
  objects.push('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj');
  
  // Object 2: Pages
  objects.push('2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj');
  
  // Object 3: Page
  objects.push('3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj');
  
  // Object 4: Content stream
  objects.push(`4 0 obj\n<< /Length ${contentStream.length} >>\nstream\n${contentStream}\nendstream\nendobj`);
  
  // Object 5: Font
  objects.push('5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>\nendobj');

  // Build the PDF
  let pdf = '%PDF-1.4\n%âãÏÓ\n';
  const offsets: number[] = [];
  
  for (const obj of objects) {
    offsets.push(pdf.length);
    pdf += obj + '\n';
  }
  
  // Cross-reference table
  const xrefOffset = pdf.length;
  pdf += 'xref\n';
  pdf += `0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  
  for (const offset of offsets) {
    pdf += offset.toString().padStart(10, '0') + ' 00000 n \n';
  }
  
  // Trailer
  pdf += 'trailer\n';
  pdf += `<< /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += 'startxref\n';
  pdf += xrefOffset + '\n';
  pdf += '%%EOF';

  // Convert to ArrayBuffer for proper binary handling
  const encoder = new TextEncoder();
  return encoder.encode(pdf).buffer as ArrayBuffer;
}

// Helper to get registrant data formatted for PDF
export function formatRegistrantForPdf(registrant: {
  nameEn: string;
  email: string;
  projectTitleEn: string;
  id: string;
  registrationDate: string;
  status: string;
  grade?: Grade;
}, file: { name: string }): PdfData {
  return {
    studentName: registrant.nameEn?.replace(/_/g, ' ') || 'Unknown Student',
    studentEmail: registrant.email || 'No email provided',
    projectTitle: registrant.projectTitleEn?.replace(/_/g, ' ') || 'Unknown Project',
    submissionId: registrant.id || 'No ID',
    submissionDate: registrant.registrationDate || new Date().toISOString(),
    fileName: file.name || 'Unknown file',
    status: registrant.status || 'Unknown',
    grade: registrant.grade,
  };
}
